services:
  - type: worker
    name: sora
    branch: sora-video
    plan: standard
    envVars:
      - fromGroup: sora
    runtime: node
    startCommand: pnpm start
    buildCommand: pnpm install && tsc
