services:
  - type: worker
    name: blast
    branch: blast-ai-bot
    plan: standard
    envVars:
      - fromGroup: blastai
    runtime: node
    startCommand: pnpm start
    buildCommand: pnpm install && tsc
